name: pose
dependencies:
    - pip:
        - easydict
        - pyyaml
    - python=2.7
    - imageio=2.2.0
    - numpy=1.13.3
    - h5py=2.7.1
    - tensorflow-gpu=1.3.0
    - keras=2.0.8
    - scikit-learn=0.19.1
    - scikit-image=0.13.1
    - opencv3=3.1.0
    - boto3=1.4.7
    - botocore=1.5.83
    - awscli=1.11.120
    - jupyter
channels:
    - conda-forge
    - https://conda.anaconda.org/menpo